<?PHP
//	include("../Main.php");

$S = 'fff ';
		echo $S; 
　//echo trim($str);
	
/*
	function a(){
		$S = "fff";
		echo $S; 
		echo"</br>";
	}

	a();

	//連線
	_dbconnect();

	echo "test php";    echo '<hr>';
	$UNO = $_GET["UNO"];
	//echo($UNO);

	function item_new(){
		$query="INSERT INTO TB_LIST (UNO,LNO,GNO,CONTENT,CREATEDAY,AUTHOR,ONCHECK) 
				VALUES ('".$_GET['']."', '".$_GET['Insert_TITLE']."')"; 
		$stid = _SQLOpen($GLOBALS['db'],$query);
		return $stid;
	}


	function GETVAULE(){
		$UNO = $_GET["UNO"];
		echo "HELLO";
		echo  $UNO;
	}

*/


?>